apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-aks
  labels:
    app: deploy-aks
  namespace: namespace-workflow-1688359866576
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-aks
  template:
    metadata:
      labels:
        app: deploy-aks
    spec:
      containers:
        - name: deploy-aks
          image: acrworkflow1688359866576.azurecr.io/image-workflow-1688359866576:latest
          ports:
            - containerPort: 8000