apiVersion: v1
kind: Service
metadata:
  name: deploy-aks
  namespace: namespace-workflow-1688359866576
spec:
  type: LoadBalancer
  selector:
    app: deploy-aks
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000