name: Test Docker Image

on:
  pull_request:

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-flask-app:${{ github.sha }} .
      - name: Test Docker image
        run: |
          docker run -d --name my-flask-app my-flask-app:${{ github.sha }}
          sleep 5
          curl http://localhost:5000/
          exit
