name: Test Docker Image

on:
  pull_request:

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-flask-app:${{ github.sha }} .
      - name: Test Docker image
        run: docker run my-flask-app:${{ github.sha }}
      - name: Test Docker Image
      # You may pin to the exact commit or the version.
      # uses: jina-ai/action-hubble-test-docker@711374770bc94ef16ca6c2c39af30142d9b864c2
        uses: jina-ai/action-hubble-test-docker@v6
