name: Test Docker Image

on:
  pull_request:

jobs:
  test-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: |
          docker build -t my-flask-app:${{ github.sha }} .
          docker images

      - name: Run Docker container
        run: docker run -d --name my-flask-app my-flask-app:${{ github.sha }}

      - name: Wait for container to start
        run: sleep 5

      - name: Test Docker image
        run: curl http://localhost:5000/

      - name: Stop and remove Docker container
        run: docker stop my-flask-app && docker rm my-flask-app
